// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	models "github.com/jimi024rion/todo-go/models"
)

type Factory struct {
	baseTodoMods TodoModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewTodo(mods ...TodoMod) *TodoTemplate {
	return f.NewTodoWithContext(context.Background(), mods...)
}

func (f *Factory) NewTodoWithContext(ctx context.Context, mods ...TodoMod) *TodoTemplate {
	o := &TodoTemplate{f: f}

	if f != nil {
		f.baseTodoMods.Apply(ctx, o)
	}

	TodoModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingTodo(m *models.Todo) *TodoTemplate {
	o := &TodoTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.Title = func() string { return m.Title }
	o.Description = func() null.Val[string] { return m.Description }
	o.Completed = func() bool { return m.Completed }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	return o
}

func (f *Factory) ClearBaseTodoMods() {
	f.baseTodoMods = nil
}

func (f *Factory) AddBaseTodoMod(mods ...TodoMod) {
	f.baseTodoMods = append(f.baseTodoMods, mods...)
}
