// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jimi024rion/todo-go/backend/internal/domain/todo/model/entity"
	"github.com/jimi024rion/todo-go/backend/internal/domain/todo/model/valueobject"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTodoRepository creates a new instance of MockTodoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoRepository {
	mock := &MockTodoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoRepository is an autogenerated mock type for the TodoRepository type
type MockTodoRepository struct {
	mock.Mock
}

type MockTodoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoRepository) EXPECT() *MockTodoRepository_Expecter {
	return &MockTodoRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) Delete(ctx context.Context, id valueobject.TodoID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.TodoID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTodoRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobject.TodoID
func (_e *MockTodoRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTodoRepository_Delete_Call {
	return &MockTodoRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTodoRepository_Delete_Call) Run(run func(ctx context.Context, id valueobject.TodoID)) *MockTodoRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.TodoID
		if args[1] != nil {
			arg1 = args[1].(valueobject.TodoID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_Delete_Call) Return(err error) *MockTodoRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id valueobject.TodoID) error) *MockTodoRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) FindByID(ctx context.Context, id valueobject.TodoID) (*entity.Todo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.TodoID) (*entity.Todo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.TodoID) *entity.Todo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.TodoID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTodoRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobject.TodoID
func (_e *MockTodoRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTodoRepository_FindByID_Call {
	return &MockTodoRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTodoRepository_FindByID_Call) Run(run func(ctx context.Context, id valueobject.TodoID)) *MockTodoRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.TodoID
		if args[1] != nil {
			arg1 = args[1].(valueobject.TodoID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_FindByID_Call) Return(todo *entity.Todo, err error) *MockTodoRepository_FindByID_Call {
	_c.Call.Return(todo, err)
	return _c
}

func (_c *MockTodoRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id valueobject.TodoID) (*entity.Todo, error)) *MockTodoRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) List(ctx context.Context) ([]*entity.Todo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Todo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Todo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTodoRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTodoRepository_Expecter) List(ctx interface{}) *MockTodoRepository_List_Call {
	return &MockTodoRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTodoRepository_List_Call) Run(run func(ctx context.Context)) *MockTodoRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTodoRepository_List_Call) Return(todos []*entity.Todo, err error) *MockTodoRepository_List_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *MockTodoRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Todo, error)) *MockTodoRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTodoRepository
func (_mock *MockTodoRepository) Save(ctx context.Context, todo *entity.Todo) error {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Todo) error); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTodoRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - todo *entity.Todo
func (_e *MockTodoRepository_Expecter) Save(ctx interface{}, todo interface{}) *MockTodoRepository_Save_Call {
	return &MockTodoRepository_Save_Call{Call: _e.mock.On("Save", ctx, todo)}
}

func (_c *MockTodoRepository_Save_Call) Run(run func(ctx context.Context, todo *entity.Todo)) *MockTodoRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Todo
		if args[1] != nil {
			arg1 = args[1].(*entity.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoRepository_Save_Call) Return(err error) *MockTodoRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoRepository_Save_Call) RunAndReturn(run func(ctx context.Context, todo *entity.Todo) error) *MockTodoRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
