// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jimi024rion/todo-go/backend/internal/domain/tag/model/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTagRepository creates a new instance of MockTagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagRepository {
	mock := &MockTagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTagRepository is an autogenerated mock type for the TagRepository type
type MockTagRepository struct {
	mock.Mock
}

type MockTagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagRepository) EXPECT() *MockTagRepository_Expecter {
	return &MockTagRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) Create(ctx context.Context, tag *entity.Tag) error {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Tag) error); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTagRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tag *entity.Tag
func (_e *MockTagRepository_Expecter) Create(ctx interface{}, tag interface{}) *MockTagRepository_Create_Call {
	return &MockTagRepository_Create_Call{Call: _e.mock.On("Create", ctx, tag)}
}

func (_c *MockTagRepository_Create_Call) Run(run func(ctx context.Context, tag *entity.Tag)) *MockTagRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Tag
		if args[1] != nil {
			arg1 = args[1].(*entity.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagRepository_Create_Call) Return(err error) *MockTagRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tag *entity.Tag) error) *MockTagRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) Delete(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTagRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockTagRepository_Expecter) Delete(ctx interface{}, id interface{}, userID interface{}) *MockTagRepository_Delete_Call {
	return &MockTagRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *MockTagRepository_Delete_Call) Run(run func(ctx context.Context, id string, userID string)) *MockTagRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagRepository_Delete_Call) Return(err error) *MockTagRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *MockTagRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTodoIDs provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) FindByTodoIDs(ctx context.Context, todoIDs []string) (map[string][]*entity.Tag, error) {
	ret := _mock.Called(ctx, todoIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByTodoIDs")
	}

	var r0 map[string][]*entity.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string][]*entity.Tag, error)); ok {
		return returnFunc(ctx, todoIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string][]*entity.Tag); ok {
		r0 = returnFunc(ctx, todoIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]*entity.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, todoIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagRepository_FindByTodoIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTodoIDs'
type MockTagRepository_FindByTodoIDs_Call struct {
	*mock.Call
}

// FindByTodoIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - todoIDs []string
func (_e *MockTagRepository_Expecter) FindByTodoIDs(ctx interface{}, todoIDs interface{}) *MockTagRepository_FindByTodoIDs_Call {
	return &MockTagRepository_FindByTodoIDs_Call{Call: _e.mock.On("FindByTodoIDs", ctx, todoIDs)}
}

func (_c *MockTagRepository_FindByTodoIDs_Call) Run(run func(ctx context.Context, todoIDs []string)) *MockTagRepository_FindByTodoIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagRepository_FindByTodoIDs_Call) Return(stringToTags map[string][]*entity.Tag, err error) *MockTagRepository_FindByTodoIDs_Call {
	_c.Call.Return(stringToTags, err)
	return _c
}

func (_c *MockTagRepository_FindByTodoIDs_Call) RunAndReturn(run func(ctx context.Context, todoIDs []string) (map[string][]*entity.Tag, error)) *MockTagRepository_FindByTodoIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) FindByUserID(ctx context.Context, userID string) ([]*entity.Tag, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*entity.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Tag, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Tag); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTagRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockTagRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTagRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockTagRepository_FindByUserID_Call {
	return &MockTagRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockTagRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockTagRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTagRepository_FindByUserID_Call) Return(tags []*entity.Tag, err error) *MockTagRepository_FindByUserID_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockTagRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Tag, error)) *MockTagRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SetTodoTags provides a mock function for the type MockTagRepository
func (_mock *MockTagRepository) SetTodoTags(ctx context.Context, todoID string, tagIDs []string) error {
	ret := _mock.Called(ctx, todoID, tagIDs)

	if len(ret) == 0 {
		panic("no return value specified for SetTodoTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, todoID, tagIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagRepository_SetTodoTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTodoTags'
type MockTagRepository_SetTodoTags_Call struct {
	*mock.Call
}

// SetTodoTags is a helper method to define mock.On call
//   - ctx context.Context
//   - todoID string
//   - tagIDs []string
func (_e *MockTagRepository_Expecter) SetTodoTags(ctx interface{}, todoID interface{}, tagIDs interface{}) *MockTagRepository_SetTodoTags_Call {
	return &MockTagRepository_SetTodoTags_Call{Call: _e.mock.On("SetTodoTags", ctx, todoID, tagIDs)}
}

func (_c *MockTagRepository_SetTodoTags_Call) Run(run func(ctx context.Context, todoID string, tagIDs []string)) *MockTagRepository_SetTodoTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTagRepository_SetTodoTags_Call) Return(err error) *MockTagRepository_SetTodoTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagRepository_SetTodoTags_Call) RunAndReturn(run func(ctx context.Context, todoID string, tagIDs []string) error) *MockTagRepository_SetTodoTags_Call {
	_c.Call.Return(run)
	return _c
}
