// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var APIKeyErrors = &apiKeyErrors{
	ErrUniqueApiKeysPkey: &UniqueConstraintError{
		schema:  "",
		table:   "api_keys",
		columns: []string{"id"},
		s:       "api_keys_pkey",
	},

	ErrUniqueApiKeysKeyHashKey: &UniqueConstraintError{
		schema:  "",
		table:   "api_keys",
		columns: []string{"key_hash"},
		s:       "api_keys_key_hash_key",
	},
}

type apiKeyErrors struct {
	ErrUniqueApiKeysPkey *UniqueConstraintError

	ErrUniqueApiKeysKeyHashKey *UniqueConstraintError
}
