// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TagErrors = &tagErrors{
	ErrUniqueTagsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "tags",
		columns: []string{"id"},
		s:       "tags_pkey",
	},
}

type tagErrors struct {
	ErrUniqueTagsPkey *UniqueConstraintError
}
