// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TodoTagErrors = &todoTagErrors{
	ErrUniqueTodoTagsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "todo_tags",
		columns: []string{"todo_id", "tag_id"},
		s:       "todo_tags_pkey",
	},
}

type todoTagErrors struct {
	ErrUniqueTodoTagsPkey *UniqueConstraintError
}
