// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"github.com/jimi024rion/todo-go/backend/internal/infrastructure/repository/todo"
	"github.com/jimi024rion/todo-go/backend/internal/presentation/handler"
	"github.com/jimi024rion/todo-go/backend/internal/presentation/http"
	"github.com/jimi024rion/todo-go/backend/internal/presentation/http/health"
	todo3 "github.com/jimi024rion/todo-go/backend/internal/presentation/http/todo"
	todo2 "github.com/jimi024rion/todo-go/backend/internal/usecase/todo"
)

// Injectors from wire.go:

// InitializeServer initializes the Gin engine with all its dependencies.
func InitializeServer() (*gin.Engine, func(), error) {
	healthCheckHandler := health.NewHealthCheckHandler()
	healthHandler := health.NewHandler(healthCheckHandler)
	dummyRepository := todo.NewDummyRepository()
	listUseCase := todo2.NewListUseCase(dummyRepository)
	listHandler := todo3.NewListHandler(listUseCase)
	createUseCase := todo2.NewCreateUseCase(dummyRepository)
	createHandler := todo3.NewCreateHandler(createUseCase)
	getUseCase := todo2.NewGetUseCase(dummyRepository)
	getHandler := todo3.NewGetHandler(getUseCase)
	updateUseCase := todo2.NewUpdateUseCase(dummyRepository)
	updateHandler := todo3.NewUpdateHandler(updateUseCase)
	deleteUseCase := todo2.NewDeleteUseCase(dummyRepository)
	deleteHandler := todo3.NewDeleteHandler(deleteUseCase)
	todoHandler := todo3.NewHandler(listHandler, createHandler, getHandler, updateHandler, deleteHandler)
	handlerHandler := handler.NewHandler(healthHandler, todoHandler)
	engine := http.NewRouter(handlerHandler)
	return engine, func() {
	}, nil
}
