// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"github.com/jimi024rion/todo-go/backend/internal/presentation/handler"
	"github.com/jimi024rion/todo-go/backend/internal/presentation/http"
	"github.com/jimi024rion/todo-go/backend/internal/presentation/http/health"
	"github.com/jimi024rion/todo-go/backend/internal/presentation/http/todo"
)

// Injectors from wire.go:

// InitializeServer initializes the Gin engine with all its dependencies.
func InitializeServer() (*gin.Engine, func(), error) {
	healthCheckHandler := health.NewHealthCheckHandler()
	healthHandler := health.NewHandler(healthCheckHandler)
	listHandler := todo.NewListHandler()
	createHandler := todo.NewCreateHandler()
	getHandler := todo.NewGetHandler()
	updateHandler := todo.NewUpdateHandler()
	deleteHandler := todo.NewDeleteHandler()
	todoHandler := todo.NewHandler(listHandler, createHandler, getHandler, updateHandler, deleteHandler)
	handlerHandler := handler.NewHandler(healthHandler, todoHandler)
	engine := http.NewRouter(handlerHandler)
	return engine, func() {
	}, nil
}
