// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "サーバーの稼働状況を確認します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "ヘルスチェック",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/v1/api-keys": {
            "post": {
                "description": "新しいAPIキーを発行します（認証不要）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "APIキー作成",
                "parameters": [
                    {
                        "description": "APIキー作成リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ApiKeyCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/ApiKeyCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ApiKeyCreateErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/api-keys/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "指定されたIDのAPIキーを削除します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "APIキー削除",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"01234567-89ab-cdef-0123-456789abcdef\"",
                        "description": "APIキーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    }
                }
            }
        },
        "/v1/todos": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "すべてのタスクを一覧で取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "タスク一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TodoListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "新しいタスクを作成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "タスク作成",
                "parameters": [
                    {
                        "description": "タスク作成リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/TodoCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/TodoCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    }
                }
            }
        },
        "/v1/todos/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "指定されたIDのタスクを取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "タスク詳細取得",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"01234567-89ab-cdef-0123-456789abcdef\"",
                        "description": "タスクID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TodoGetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "指定されたIDのタスクを更新します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "タスク更新",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"01234567-89ab-cdef-0123-456789abcdef\"",
                        "description": "タスクID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "タスク更新リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/TodoUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TodoGetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "指定されたIDのタスクを削除します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "todos"
                ],
                "summary": "タスク削除",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"01234567-89ab-cdef-0123-456789abcdef\"",
                        "description": "タスクID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "新しいユーザーを作成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "ユーザー作成",
                "parameters": [
                    {
                        "description": "ユーザー作成リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/UserCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorNullResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ApiKeyCreateErrorResponse": {
            "type": "object",
            "properties": {
                "resultBody": {
                    "$ref": "#/definitions/ApiKeyItemErr"
                },
                "resultHeader": {
                    "$ref": "#/definitions/ResultHeader"
                }
            }
        },
        "ApiKeyCreateRequest": {
            "type": "object",
            "required": [
                "name",
                "user_id"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1,
                    "example": "My API Key"
                },
                "user_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "01234567-89ab-cdef-0123-456789abcdef"
                }
            }
        },
        "ApiKeyCreateResponse": {
            "type": "object",
            "properties": {
                "resultBody": {
                    "$ref": "#/definitions/ApiKeyItem"
                },
                "resultHeader": {
                    "$ref": "#/definitions/ResultHeader"
                }
            }
        },
        "ApiKeyItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "01234567-89ab-cdef-0123-456789abcdef"
                },
                "key": {
                    "type": "string",
                    "example": "todo_abc123..."
                },
                "name": {
                    "type": "string",
                    "example": "My API Key"
                },
                "user_id": {
                    "type": "string",
                    "example": "01234567-89ab-cdef-0123-456789abcdef"
                }
            }
        },
        "ApiKeyItemErr": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "key": {
                    "type": "string",
                    "example": ""
                },
                "name": {
                    "type": "string",
                    "example": ""
                },
                "user_id": {
                    "type": "string",
                    "example": ""
                }
            }
        },
        "ErrorNullResponse": {
            "type": "object",
            "properties": {
                "resultBody": {
                    "type": "object"
                },
                "resultHeader": {
                    "$ref": "#/definitions/ResultHeader"
                }
            }
        },
        "HealthCheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "ResultHeader": {
            "type": "object",
            "properties": {
                "resultCode": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "TodoCreateBody": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "01234567-89ab-cdef-0123-456789abcdef"
                }
            }
        },
        "TodoCreateRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "牛乳、卵、パンを買う"
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "買い物リストを作る"
                }
            }
        },
        "TodoCreateResponse": {
            "type": "object",
            "properties": {
                "resultBody": {
                    "$ref": "#/definitions/TodoCreateBody"
                },
                "resultHeader": {
                    "$ref": "#/definitions/ResultHeader"
                }
            }
        },
        "TodoGetResponse": {
            "type": "object",
            "properties": {
                "resultBody": {
                    "$ref": "#/definitions/TodoItem"
                },
                "resultHeader": {
                    "$ref": "#/definitions/ResultHeader"
                }
            }
        },
        "TodoItem": {
            "type": "object",
            "properties": {
                "CreatedAt": {
                    "type": "string"
                },
                "Description": {
                    "type": "string",
                    "example": "牛乳、卵、パンを買う"
                },
                "ID": {
                    "type": "string",
                    "example": "01234567-89ab-cdef-0123-456789abcdef"
                },
                "Status": {
                    "type": "string",
                    "example": "pending"
                },
                "Title": {
                    "type": "string",
                    "example": "買い物リストを作る"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "TodoListResponse": {
            "type": "object",
            "properties": {
                "resultBody": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TodoItem"
                    }
                },
                "resultHeader": {
                    "$ref": "#/definitions/ResultHeader"
                }
            }
        },
        "TodoUpdateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000,
                    "example": "牛乳、卵、パンを買う"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "in_progress",
                        "completed"
                    ],
                    "example": "in_progress"
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "買い物リストを作る"
                }
            }
        },
        "UserCreateRequest": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "john@example.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "John Doe"
                }
            }
        },
        "UserCreateResponse": {
            "type": "object",
            "properties": {
                "resultBody": {
                    "$ref": "#/definitions/UserItem"
                },
                "resultHeader": {
                    "$ref": "#/definitions/ResultHeader"
                }
            }
        },
        "UserItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "01234567-89ab-cdef-0123-456789abcdef"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "X-API-Keyヘッダーにトークンを設定してください",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Todo API",
	Description:      "Todo管理アプリケーションのREST API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
