// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jimi024rion/todo-go/backend/internal/domain/apikey/model/entity"
	"github.com/jimi024rion/todo-go/backend/internal/domain/apikey/model/valueobject"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIKeyRepository creates a new instance of MockAPIKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeyRepository is an autogenerated mock type for the APIKeyRepository type
type MockAPIKeyRepository struct {
	mock.Mock
}

type MockAPIKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepository_Expecter {
	return &MockAPIKeyRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) Delete(ctx context.Context, id valueobject.APIKeyID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.APIKeyID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAPIKeyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id valueobject.APIKeyID
func (_e *MockAPIKeyRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAPIKeyRepository_Delete_Call {
	return &MockAPIKeyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAPIKeyRepository_Delete_Call) Run(run func(ctx context.Context, id valueobject.APIKeyID)) *MockAPIKeyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.APIKeyID
		if args[1] != nil {
			arg1 = args[1].(valueobject.APIKeyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_Delete_Call) Return(err error) *MockAPIKeyRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id valueobject.APIKeyID) error) *MockAPIKeyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByKeyHash provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) FindByKeyHash(ctx context.Context, keyHash string) (*entity.APIKey, error) {
	ret := _mock.Called(ctx, keyHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByKeyHash")
	}

	var r0 *entity.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.APIKey, error)); ok {
		return returnFunc(ctx, keyHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.APIKey); ok {
		r0 = returnFunc(ctx, keyHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, keyHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyRepository_FindByKeyHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByKeyHash'
type MockAPIKeyRepository_FindByKeyHash_Call struct {
	*mock.Call
}

// FindByKeyHash is a helper method to define mock.On call
//   - ctx context.Context
//   - keyHash string
func (_e *MockAPIKeyRepository_Expecter) FindByKeyHash(ctx interface{}, keyHash interface{}) *MockAPIKeyRepository_FindByKeyHash_Call {
	return &MockAPIKeyRepository_FindByKeyHash_Call{Call: _e.mock.On("FindByKeyHash", ctx, keyHash)}
}

func (_c *MockAPIKeyRepository_FindByKeyHash_Call) Run(run func(ctx context.Context, keyHash string)) *MockAPIKeyRepository_FindByKeyHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_FindByKeyHash_Call) Return(aPIKey *entity.APIKey, err error) *MockAPIKeyRepository_FindByKeyHash_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyRepository_FindByKeyHash_Call) RunAndReturn(run func(ctx context.Context, keyHash string) (*entity.APIKey, error)) *MockAPIKeyRepository_FindByKeyHash_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) Save(ctx context.Context, apiKey *entity.APIKey) error {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.APIKey) error); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAPIKeyRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey *entity.APIKey
func (_e *MockAPIKeyRepository_Expecter) Save(ctx interface{}, apiKey interface{}) *MockAPIKeyRepository_Save_Call {
	return &MockAPIKeyRepository_Save_Call{Call: _e.mock.On("Save", ctx, apiKey)}
}

func (_c *MockAPIKeyRepository_Save_Call) Run(run func(ctx context.Context, apiKey *entity.APIKey)) *MockAPIKeyRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.APIKey
		if args[1] != nil {
			arg1 = args[1].(*entity.APIKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_Save_Call) Return(err error) *MockAPIKeyRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyRepository_Save_Call) RunAndReturn(run func(ctx context.Context, apiKey *entity.APIKey) error) *MockAPIKeyRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
