// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jimi024rion/todo-go/backend/internal/domain/apikey/model/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIKeyCache creates a new instance of MockAPIKeyCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyCache {
	mock := &MockAPIKeyCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeyCache is an autogenerated mock type for the APIKeyCache type
type MockAPIKeyCache struct {
	mock.Mock
}

type MockAPIKeyCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyCache) EXPECT() *MockAPIKeyCache_Expecter {
	return &MockAPIKeyCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockAPIKeyCache
func (_mock *MockAPIKeyCache) Delete(ctx context.Context, key string) {
	_mock.Called(ctx, key)
	return
}

// MockAPIKeyCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAPIKeyCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAPIKeyCache_Expecter) Delete(ctx interface{}, key interface{}) *MockAPIKeyCache_Delete_Call {
	return &MockAPIKeyCache_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockAPIKeyCache_Delete_Call) Run(run func(ctx context.Context, key string)) *MockAPIKeyCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyCache_Delete_Call) Return() *MockAPIKeyCache_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAPIKeyCache_Delete_Call) RunAndReturn(run func(ctx context.Context, key string)) *MockAPIKeyCache_Delete_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockAPIKeyCache
func (_mock *MockAPIKeyCache) Get(ctx context.Context, key string) (*entity.APIKey, bool) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.APIKey
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.APIKey, bool)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.APIKey); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockAPIKeyCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAPIKeyCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAPIKeyCache_Expecter) Get(ctx interface{}, key interface{}) *MockAPIKeyCache_Get_Call {
	return &MockAPIKeyCache_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockAPIKeyCache_Get_Call) Run(run func(ctx context.Context, key string)) *MockAPIKeyCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyCache_Get_Call) Return(aPIKey *entity.APIKey, b bool) *MockAPIKeyCache_Get_Call {
	_c.Call.Return(aPIKey, b)
	return _c
}

func (_c *MockAPIKeyCache_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (*entity.APIKey, bool)) *MockAPIKeyCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockAPIKeyCache
func (_mock *MockAPIKeyCache) Set(ctx context.Context, key string, apiKey *entity.APIKey) {
	_mock.Called(ctx, key, apiKey)
	return
}

// MockAPIKeyCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockAPIKeyCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - apiKey *entity.APIKey
func (_e *MockAPIKeyCache_Expecter) Set(ctx interface{}, key interface{}, apiKey interface{}) *MockAPIKeyCache_Set_Call {
	return &MockAPIKeyCache_Set_Call{Call: _e.mock.On("Set", ctx, key, apiKey)}
}

func (_c *MockAPIKeyCache_Set_Call) Run(run func(ctx context.Context, key string, apiKey *entity.APIKey)) *MockAPIKeyCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *entity.APIKey
		if args[2] != nil {
			arg2 = args[2].(*entity.APIKey)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIKeyCache_Set_Call) Return() *MockAPIKeyCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAPIKeyCache_Set_Call) RunAndReturn(run func(ctx context.Context, key string, apiKey *entity.APIKey)) *MockAPIKeyCache_Set_Call {
	_c.Run(run)
	return _c
}
