// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// APIKey is an object representing the database table.
type APIKey struct {
	ID        uuid.UUID `db:"id,pk" `
	UserID    uuid.UUID `db:"user_id" `
	Name      string    `db:"name" `
	CreatedAt time.Time `db:"created_at" `
	KeyHash   string    `db:"key_hash" `

	R apiKeyR `db:"-" `
}

// APIKeySlice is an alias for a slice of pointers to APIKey.
// This should almost always be used instead of []*APIKey.
type APIKeySlice []*APIKey

// APIKeys contains methods to work with the api_keys table
var APIKeys = psql.NewTablex[*APIKey, APIKeySlice, *APIKeySetter]("", "api_keys", buildAPIKeyColumns("api_keys"))

// APIKeysQuery is a query on the api_keys table
type APIKeysQuery = *psql.ViewQuery[*APIKey, APIKeySlice]

// apiKeyR is where relationships are stored.
type apiKeyR struct {
	User *User // api_keys.fk_api_keys_user_id
}

func buildAPIKeyColumns(alias string) apiKeyColumns {
	return apiKeyColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "name", "created_at", "key_hash",
		).WithParent("api_keys"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		UserID:     psql.Quote(alias, "user_id"),
		Name:       psql.Quote(alias, "name"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		KeyHash:    psql.Quote(alias, "key_hash"),
	}
}

type apiKeyColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	UserID     psql.Expression
	Name       psql.Expression
	CreatedAt  psql.Expression
	KeyHash    psql.Expression
}

func (c apiKeyColumns) Alias() string {
	return c.tableAlias
}

func (apiKeyColumns) AliasedAs(alias string) apiKeyColumns {
	return buildAPIKeyColumns(alias)
}

// APIKeySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type APIKeySetter struct {
	ID        omit.Val[uuid.UUID] `db:"id,pk" `
	UserID    omit.Val[uuid.UUID] `db:"user_id" `
	Name      omit.Val[string]    `db:"name" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	KeyHash   omit.Val[string]    `db:"key_hash" `
}

func (s APIKeySetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.KeyHash.IsValue() {
		vals = append(vals, "key_hash")
	}
	return vals
}

func (s APIKeySetter) Overwrite(t *APIKey) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.KeyHash.IsValue() {
		t.KeyHash = s.KeyHash.MustGet()
	}
}

func (s *APIKeySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return APIKeys.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[3] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.KeyHash.IsValue() {
			vals[4] = psql.Arg(s.KeyHash.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s APIKeySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s APIKeySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.KeyHash.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "key_hash")...),
			psql.Arg(s.KeyHash),
		}})
	}

	return exprs
}

// FindAPIKey retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAPIKey(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*APIKey, error) {
	if len(cols) == 0 {
		return APIKeys.Query(
			sm.Where(APIKeys.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return APIKeys.Query(
		sm.Where(APIKeys.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(APIKeys.Columns.Only(cols...)),
	).One(ctx, exec)
}

// APIKeyExists checks the presence of a single record by primary key
func APIKeyExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return APIKeys.Query(
		sm.Where(APIKeys.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after APIKey is retrieved from the database
func (o *APIKey) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = APIKeys.AfterSelectHooks.RunHooks(ctx, exec, APIKeySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = APIKeys.AfterInsertHooks.RunHooks(ctx, exec, APIKeySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = APIKeys.AfterUpdateHooks.RunHooks(ctx, exec, APIKeySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = APIKeys.AfterDeleteHooks.RunHooks(ctx, exec, APIKeySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the APIKey
func (o *APIKey) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *APIKey) pkEQ() dialect.Expression {
	return psql.Quote("api_keys", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the APIKey
func (o *APIKey) Update(ctx context.Context, exec bob.Executor, s *APIKeySetter) error {
	v, err := APIKeys.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single APIKey record with an executor
func (o *APIKey) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := APIKeys.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the APIKey using the executor
func (o *APIKey) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := APIKeys.Query(
		sm.Where(APIKeys.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after APIKeySlice is retrieved from the database
func (o APIKeySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = APIKeys.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = APIKeys.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = APIKeys.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = APIKeys.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o APIKeySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("api_keys", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o APIKeySlice) copyMatchingRows(from ...*APIKey) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o APIKeySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return APIKeys.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *APIKey:
				o.copyMatchingRows(retrieved)
			case []*APIKey:
				o.copyMatchingRows(retrieved...)
			case APIKeySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a APIKey or a slice of APIKey
				// then run the AfterUpdateHooks on the slice
				_, err = APIKeys.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o APIKeySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return APIKeys.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *APIKey:
				o.copyMatchingRows(retrieved)
			case []*APIKey:
				o.copyMatchingRows(retrieved...)
			case APIKeySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a APIKey or a slice of APIKey
				// then run the AfterDeleteHooks on the slice
				_, err = APIKeys.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o APIKeySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals APIKeySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := APIKeys.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o APIKeySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := APIKeys.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o APIKeySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := APIKeys.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *APIKey) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os APIKeySlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachAPIKeyUser0(ctx context.Context, exec bob.Executor, count int, apiKey0 *APIKey, user1 *User) (*APIKey, error) {
	setter := &APIKeySetter{
		UserID: omit.From(user1.ID),
	}

	err := apiKey0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAPIKeyUser0: %w", err)
	}

	return apiKey0, nil
}

func (apiKey0 *APIKey) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachAPIKeyUser0(ctx, exec, 1, apiKey0, user1)
	if err != nil {
		return err
	}

	apiKey0.R.User = user1

	user1.R.APIKeys = append(user1.R.APIKeys, apiKey0)

	return nil
}

func (apiKey0 *APIKey) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachAPIKeyUser0(ctx, exec, 1, apiKey0, user1)
	if err != nil {
		return err
	}

	apiKey0.R.User = user1

	user1.R.APIKeys = append(user1.R.APIKeys, apiKey0)

	return nil
}

type apiKeyWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, uuid.UUID]
	UserID    psql.WhereMod[Q, uuid.UUID]
	Name      psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	KeyHash   psql.WhereMod[Q, string]
}

func (apiKeyWhere[Q]) AliasedAs(alias string) apiKeyWhere[Q] {
	return buildAPIKeyWhere[Q](buildAPIKeyColumns(alias))
}

func buildAPIKeyWhere[Q psql.Filterable](cols apiKeyColumns) apiKeyWhere[Q] {
	return apiKeyWhere[Q]{
		ID:        psql.Where[Q, uuid.UUID](cols.ID),
		UserID:    psql.Where[Q, uuid.UUID](cols.UserID),
		Name:      psql.Where[Q, string](cols.Name),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		KeyHash:   psql.Where[Q, string](cols.KeyHash),
	}
}

func (o *APIKey) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("apiKey cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.APIKeys = APIKeySlice{o}
		}
		return nil
	default:
		return fmt.Errorf("apiKey has no relationship %q", name)
	}
}

type apiKeyPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildAPIKeyPreloader() apiKeyPreloader {
	return apiKeyPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        APIKeys,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type apiKeyThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildAPIKeyThenLoader[Q orm.Loadable]() apiKeyThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return apiKeyThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the apiKey's User into the .R struct
func (o *APIKey) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.APIKeys = APIKeySlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the apiKey's User into the .R struct
func (os APIKeySlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.APIKeys = append(rel.R.APIKeys, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type apiKeyJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j apiKeyJoins[Q]) aliasedAs(alias string) apiKeyJoins[Q] {
	return buildAPIKeyJoins[Q](buildAPIKeyColumns(alias), j.typ)
}

func buildAPIKeyJoins[Q dialect.Joinable](cols apiKeyColumns, typ string) apiKeyJoins[Q] {
	return apiKeyJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
