// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"

	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type APIKey runs hooks after queries
var _ bob.HookableType = &APIKey{}

// Make sure the type Tag runs hooks after queries
var _ bob.HookableType = &Tag{}

// Make sure the type TodoTag runs hooks after queries
var _ bob.HookableType = &TodoTag{}

// Make sure the type Todo runs hooks after queries
var _ bob.HookableType = &Todo{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}

// Make sure the type uuid.UUID satisfies database/sql.Scanner
var _ sql.Scanner = (*uuid.UUID)(nil)

// Make sure the type uuid.UUID satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(uuid.UUID)
