// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// Tag is an object representing the database table.
type Tag struct {
	ID        uuid.UUID `db:"id,pk" `
	UserID    uuid.UUID `db:"user_id" `
	Name      string    `db:"name" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R tagR `db:"-" `
}

// TagSlice is an alias for a slice of pointers to Tag.
// This should almost always be used instead of []*Tag.
type TagSlice []*Tag

// Tags contains methods to work with the tags table
var Tags = psql.NewTablex[*Tag, TagSlice, *TagSetter]("", "tags", buildTagColumns("tags"))

// TagsQuery is a query on the tags table
type TagsQuery = *psql.ViewQuery[*Tag, TagSlice]

// tagR is where relationships are stored.
type tagR struct {
	User  *User     // tags.tags_user_id_fkey
	Todos TodoSlice // todo_tags.todo_tags_tag_id_fkeytodo_tags.todo_tags_todo_id_fkey
}

func buildTagColumns(alias string) tagColumns {
	return tagColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "name", "created_at", "updated_at",
		).WithParent("tags"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		UserID:     psql.Quote(alias, "user_id"),
		Name:       psql.Quote(alias, "name"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type tagColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	UserID     psql.Expression
	Name       psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c tagColumns) Alias() string {
	return c.tableAlias
}

func (tagColumns) AliasedAs(alias string) tagColumns {
	return buildTagColumns(alias)
}

// TagSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TagSetter struct {
	ID        omit.Val[uuid.UUID] `db:"id,pk" `
	UserID    omit.Val[uuid.UUID] `db:"user_id" `
	Name      omit.Val[string]    `db:"name" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s TagSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s TagSetter) Overwrite(t *Tag) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *TagSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Tags.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[3] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[4] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s TagSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TagSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindTag retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTag(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Tag, error) {
	if len(cols) == 0 {
		return Tags.Query(
			sm.Where(Tags.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Tags.Query(
		sm.Where(Tags.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Tags.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TagExists checks the presence of a single record by primary key
func TagExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Tags.Query(
		sm.Where(Tags.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Tag is retrieved from the database
func (o *Tag) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tags.AfterSelectHooks.RunHooks(ctx, exec, TagSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Tags.AfterInsertHooks.RunHooks(ctx, exec, TagSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Tags.AfterUpdateHooks.RunHooks(ctx, exec, TagSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Tags.AfterDeleteHooks.RunHooks(ctx, exec, TagSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Tag
func (o *Tag) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Tag) pkEQ() dialect.Expression {
	return psql.Quote("tags", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Tag
func (o *Tag) Update(ctx context.Context, exec bob.Executor, s *TagSetter) error {
	v, err := Tags.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Tag record with an executor
func (o *Tag) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Tags.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Tag using the executor
func (o *Tag) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Tags.Query(
		sm.Where(Tags.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TagSlice is retrieved from the database
func (o TagSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tags.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Tags.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Tags.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Tags.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TagSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("tags", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TagSlice) copyMatchingRows(from ...*Tag) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TagSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tags.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Tag:
				o.copyMatchingRows(retrieved)
			case []*Tag:
				o.copyMatchingRows(retrieved...)
			case TagSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Tag or a slice of Tag
				// then run the AfterUpdateHooks on the slice
				_, err = Tags.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TagSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tags.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Tag:
				o.copyMatchingRows(retrieved)
			case []*Tag:
				o.copyMatchingRows(retrieved...)
			case TagSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Tag or a slice of Tag
				// then run the AfterDeleteHooks on the slice
				_, err = Tags.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TagSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TagSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tags.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TagSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tags.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TagSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Tags.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *Tag) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os TagSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Todos starts a query for related objects on todos
func (o *Tag) Todos(mods ...bob.Mod[*dialect.SelectQuery]) TodosQuery {
	return Todos.Query(append(mods,
		sm.InnerJoin(TodoTags.NameAs()).On(
			Todos.Columns.ID.EQ(TodoTags.Columns.TodoID)),
		sm.Where(TodoTags.Columns.TagID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os TagSlice) Todos(mods ...bob.Mod[*dialect.SelectQuery]) TodosQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Todos.Query(append(mods,
		sm.InnerJoin(TodoTags.NameAs()).On(
			Todos.Columns.ID.EQ(TodoTags.Columns.TodoID),
		),
		sm.Where(psql.Group(TodoTags.Columns.TagID).OP("IN", PKArgExpr)),
	)...)
}

func attachTagUser0(ctx context.Context, exec bob.Executor, count int, tag0 *Tag, user1 *User) (*Tag, error) {
	setter := &TagSetter{
		UserID: omit.From(user1.ID),
	}

	err := tag0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTagUser0: %w", err)
	}

	return tag0, nil
}

func (tag0 *Tag) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTagUser0(ctx, exec, 1, tag0, user1)
	if err != nil {
		return err
	}

	tag0.R.User = user1

	user1.R.Tags = append(user1.R.Tags, tag0)

	return nil
}

func (tag0 *Tag) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachTagUser0(ctx, exec, 1, tag0, user1)
	if err != nil {
		return err
	}

	tag0.R.User = user1

	user1.R.Tags = append(user1.R.Tags, tag0)

	return nil
}

func attachTagTodos0(ctx context.Context, exec bob.Executor, count int, tag0 *Tag, todos2 TodoSlice) (TodoTagSlice, error) {
	setters := make([]*TodoTagSetter, count)
	for i := range count {
		setters[i] = &TodoTagSetter{
			TagID:  omit.From(tag0.ID),
			TodoID: omit.From(todos2[i].ID),
		}
	}

	todoTags1, err := TodoTags.Insert(bob.ToMods(setters...)).All(ctx, exec)
	if err != nil {
		return nil, fmt.Errorf("attachTagTodos0: %w", err)
	}

	return todoTags1, nil
}

func (tag0 *Tag) InsertTodos(ctx context.Context, exec bob.Executor, related ...*TodoSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	inserted, err := Todos.Insert(bob.ToMods(related...)).All(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}
	todos2 := TodoSlice(inserted)

	_, err = attachTagTodos0(ctx, exec, len(related), tag0, todos2)
	if err != nil {
		return err
	}

	tag0.R.Todos = append(tag0.R.Todos, todos2...)

	for _, rel := range todos2 {
		rel.R.Tags = append(rel.R.Tags, tag0)
	}
	return nil
}

func (tag0 *Tag) AttachTodos(ctx context.Context, exec bob.Executor, related ...*Todo) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	todos2 := TodoSlice(related)

	_, err = attachTagTodos0(ctx, exec, len(related), tag0, todos2)
	if err != nil {
		return err
	}

	tag0.R.Todos = append(tag0.R.Todos, todos2...)

	for _, rel := range related {
		rel.R.Tags = append(rel.R.Tags, tag0)
	}

	return nil
}

type tagWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, uuid.UUID]
	UserID    psql.WhereMod[Q, uuid.UUID]
	Name      psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (tagWhere[Q]) AliasedAs(alias string) tagWhere[Q] {
	return buildTagWhere[Q](buildTagColumns(alias))
}

func buildTagWhere[Q psql.Filterable](cols tagColumns) tagWhere[Q] {
	return tagWhere[Q]{
		ID:        psql.Where[Q, uuid.UUID](cols.ID),
		UserID:    psql.Where[Q, uuid.UUID](cols.UserID),
		Name:      psql.Where[Q, string](cols.Name),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Tag) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("tag cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Tags = TagSlice{o}
		}
		return nil
	case "Todos":
		rels, ok := retrieved.(TodoSlice)
		if !ok {
			return fmt.Errorf("tag cannot load %T as %q", retrieved, name)
		}

		o.R.Todos = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Tags = TagSlice{o}
			}
		}
		return nil
	default:
		return fmt.Errorf("tag has no relationship %q", name)
	}
}

type tagPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildTagPreloader() tagPreloader {
	return tagPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Tags,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type tagThenLoader[Q orm.Loadable] struct {
	User  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Todos func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTagThenLoader[Q orm.Loadable]() tagThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TodosLoadInterface interface {
		LoadTodos(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return tagThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
		Todos: thenLoadBuilder[Q](
			"Todos",
			func(ctx context.Context, exec bob.Executor, retrieved TodosLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTodos(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the tag's User into the .R struct
func (o *Tag) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Tags = TagSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the tag's User into the .R struct
func (os TagSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Tags = append(rel.R.Tags, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

// LoadTodos loads the tag's Todos into the .R struct
func (o *Tag) LoadTodos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Todos = nil

	related, err := o.Todos(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Tags = TagSlice{o}
	}

	o.R.Todos = related
	return nil
}

// LoadTodos loads the tag's Todos into the .R struct
func (os TagSlice) LoadTodos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// since we are changing the columns, we need to check if the original columns were set or add the defaults
	sq := dialect.SelectQuery{}
	for _, mod := range mods {
		mod.Apply(&sq)
	}

	if len(sq.SelectList.Columns) == 0 {
		mods = append(mods, sm.Columns(Todos.Columns))
	}

	q := os.Todos(append(
		mods,
		sm.Columns(TodoTags.Columns.TagID.As("related_tags.ID")),
	)...)

	IDSlice := []uuid.UUID{}

	mapper := scan.Mod(scan.StructMapper[*Todo](), func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any, any) error) {
		return func(row *scan.Row) (any, error) {
				IDSlice = append(IDSlice, *new(uuid.UUID))
				row.ScheduleScanByName("related_tags.ID", &IDSlice[len(IDSlice)-1])

				return nil, nil
			},
			func(any, any) error {
				return nil
			}
	})

	todos, err := bob.Allx[bob.SliceTransformer[*Todo, TodoSlice]](ctx, exec, q, mapper)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Todos = nil
	}

	for _, o := range os {
		for i, rel := range todos {
			if !(o.ID == IDSlice[i]) {
				continue
			}

			rel.R.Tags = append(rel.R.Tags, o)

			o.R.Todos = append(o.R.Todos, rel)
		}
	}

	return nil
}

type tagJoins[Q dialect.Joinable] struct {
	typ   string
	User  modAs[Q, userColumns]
	Todos modAs[Q, todoColumns]
}

func (j tagJoins[Q]) aliasedAs(alias string) tagJoins[Q] {
	return buildTagJoins[Q](buildTagColumns(alias), j.typ)
}

func buildTagJoins[Q dialect.Joinable](cols tagColumns, typ string) tagJoins[Q] {
	return tagJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
		Todos: modAs[Q, todoColumns]{
			c: Todos.Columns,
			f: func(to todoColumns) bob.Mod[Q] {
				random := strconv.FormatInt(randInt(), 10)
				mods := make(mods.QueryMods[Q], 0, 2)

				{
					to := TodoTags.Columns.AliasedAs(TodoTags.Columns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, TodoTags.Name().As(to.Alias())).On(
						to.TagID.EQ(cols.ID),
					))
				}
				{
					cols := TodoTags.Columns.AliasedAs(TodoTags.Columns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, Todos.Name().As(to.Alias())).On(
						to.ID.EQ(cols.TodoID),
					))
				}

				return mods
			},
		},
	}
}
