// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// Todo is an object representing the database table.
type Todo struct {
	ID          uuid.UUID        `db:"id,pk" `
	UserID      uuid.UUID        `db:"user_id" `
	Title       string           `db:"title" `
	Description null.Val[string] `db:"description" `
	CreatedAt   time.Time        `db:"created_at" `
	UpdatedAt   time.Time        `db:"updated_at" `
	// タスクの状態 (pending, in_progress, completed)
	Status    string              `db:"status" `
	DueDate   null.Val[time.Time] `db:"due_date" `
	SortOrder float64             `db:"sort_order" `

	R todoR `db:"-" `
}

// TodoSlice is an alias for a slice of pointers to Todo.
// This should almost always be used instead of []*Todo.
type TodoSlice []*Todo

// Todos contains methods to work with the todos table
var Todos = psql.NewTablex[*Todo, TodoSlice, *TodoSetter]("", "todos", buildTodoColumns("todos"))

// TodosQuery is a query on the todos table
type TodosQuery = *psql.ViewQuery[*Todo, TodoSlice]

// todoR is where relationships are stored.
type todoR struct {
	Tags TagSlice // todo_tags.fk_todo_tags_tag_idtodo_tags.fk_todo_tags_todo_id
	User *User    // todos.fk_todos_user_id
}

func buildTodoColumns(alias string) todoColumns {
	return todoColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id", "title", "description", "created_at", "updated_at", "status", "due_date", "sort_order",
		).WithParent("todos"),
		tableAlias:  alias,
		ID:          psql.Quote(alias, "id"),
		UserID:      psql.Quote(alias, "user_id"),
		Title:       psql.Quote(alias, "title"),
		Description: psql.Quote(alias, "description"),
		CreatedAt:   psql.Quote(alias, "created_at"),
		UpdatedAt:   psql.Quote(alias, "updated_at"),
		Status:      psql.Quote(alias, "status"),
		DueDate:     psql.Quote(alias, "due_date"),
		SortOrder:   psql.Quote(alias, "sort_order"),
	}
}

type todoColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          psql.Expression
	UserID      psql.Expression
	Title       psql.Expression
	Description psql.Expression
	CreatedAt   psql.Expression
	UpdatedAt   psql.Expression
	Status      psql.Expression
	DueDate     psql.Expression
	SortOrder   psql.Expression
}

func (c todoColumns) Alias() string {
	return c.tableAlias
}

func (todoColumns) AliasedAs(alias string) todoColumns {
	return buildTodoColumns(alias)
}

// TodoSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TodoSetter struct {
	ID          omit.Val[uuid.UUID]     `db:"id,pk" `
	UserID      omit.Val[uuid.UUID]     `db:"user_id" `
	Title       omit.Val[string]        `db:"title" `
	Description omitnull.Val[string]    `db:"description" `
	CreatedAt   omit.Val[time.Time]     `db:"created_at" `
	UpdatedAt   omit.Val[time.Time]     `db:"updated_at" `
	Status      omit.Val[string]        `db:"status" `
	DueDate     omitnull.Val[time.Time] `db:"due_date" `
	SortOrder   omit.Val[float64]       `db:"sort_order" `
}

func (s TodoSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Title.IsValue() {
		vals = append(vals, "title")
	}
	if !s.Description.IsUnset() {
		vals = append(vals, "description")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	if !s.DueDate.IsUnset() {
		vals = append(vals, "due_date")
	}
	if s.SortOrder.IsValue() {
		vals = append(vals, "sort_order")
	}
	return vals
}

func (s TodoSetter) Overwrite(t *Todo) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Title.IsValue() {
		t.Title = s.Title.MustGet()
	}
	if !s.Description.IsUnset() {
		t.Description = s.Description.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
	if !s.DueDate.IsUnset() {
		t.DueDate = s.DueDate.MustGetNull()
	}
	if s.SortOrder.IsValue() {
		t.SortOrder = s.SortOrder.MustGet()
	}
}

func (s *TodoSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Todos.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 9)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Title.IsValue() {
			vals[2] = psql.Arg(s.Title.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.Description.IsUnset() {
			vals[3] = psql.Arg(s.Description.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[4] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[5] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.Status.IsValue() {
			vals[6] = psql.Arg(s.Status.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.DueDate.IsUnset() {
			vals[7] = psql.Arg(s.DueDate.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.SortOrder.IsValue() {
			vals[8] = psql.Arg(s.SortOrder.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s TodoSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TodoSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.Title.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "title")...),
			psql.Arg(s.Title),
		}})
	}

	if !s.Description.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if !s.DueDate.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "due_date")...),
			psql.Arg(s.DueDate),
		}})
	}

	if s.SortOrder.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "sort_order")...),
			psql.Arg(s.SortOrder),
		}})
	}

	return exprs
}

// FindTodo retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTodo(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Todo, error) {
	if len(cols) == 0 {
		return Todos.Query(
			sm.Where(Todos.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Todos.Query(
		sm.Where(Todos.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Todos.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TodoExists checks the presence of a single record by primary key
func TodoExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Todos.Query(
		sm.Where(Todos.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Todo is retrieved from the database
func (o *Todo) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Todos.AfterSelectHooks.RunHooks(ctx, exec, TodoSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Todos.AfterInsertHooks.RunHooks(ctx, exec, TodoSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Todos.AfterUpdateHooks.RunHooks(ctx, exec, TodoSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Todos.AfterDeleteHooks.RunHooks(ctx, exec, TodoSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Todo
func (o *Todo) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Todo) pkEQ() dialect.Expression {
	return psql.Quote("todos", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Todo
func (o *Todo) Update(ctx context.Context, exec bob.Executor, s *TodoSetter) error {
	v, err := Todos.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Todo record with an executor
func (o *Todo) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Todos.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Todo using the executor
func (o *Todo) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Todos.Query(
		sm.Where(Todos.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TodoSlice is retrieved from the database
func (o TodoSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Todos.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Todos.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Todos.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Todos.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TodoSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("todos", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TodoSlice) copyMatchingRows(from ...*Todo) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TodoSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Todos.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Todo:
				o.copyMatchingRows(retrieved)
			case []*Todo:
				o.copyMatchingRows(retrieved...)
			case TodoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Todo or a slice of Todo
				// then run the AfterUpdateHooks on the slice
				_, err = Todos.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TodoSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Todos.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Todo:
				o.copyMatchingRows(retrieved)
			case []*Todo:
				o.copyMatchingRows(retrieved...)
			case TodoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Todo or a slice of Todo
				// then run the AfterDeleteHooks on the slice
				_, err = Todos.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TodoSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TodoSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Todos.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TodoSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Todos.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TodoSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Todos.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Tags starts a query for related objects on tags
func (o *Todo) Tags(mods ...bob.Mod[*dialect.SelectQuery]) TagsQuery {
	return Tags.Query(append(mods,
		sm.InnerJoin(TodoTags.NameAs()).On(
			Tags.Columns.ID.EQ(TodoTags.Columns.TagID)),
		sm.Where(TodoTags.Columns.TodoID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os TodoSlice) Tags(mods ...bob.Mod[*dialect.SelectQuery]) TagsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Tags.Query(append(mods,
		sm.InnerJoin(TodoTags.NameAs()).On(
			Tags.Columns.ID.EQ(TodoTags.Columns.TagID),
		),
		sm.Where(psql.Group(TodoTags.Columns.TodoID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *Todo) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os TodoSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachTodoTags0(ctx context.Context, exec bob.Executor, count int, todo0 *Todo, tags2 TagSlice) (TodoTagSlice, error) {
	setters := make([]*TodoTagSetter, count)
	for i := range count {
		setters[i] = &TodoTagSetter{
			TodoID: omit.From(todo0.ID),
			TagID:  omit.From(tags2[i].ID),
		}
	}

	todoTags1, err := TodoTags.Insert(bob.ToMods(setters...)).All(ctx, exec)
	if err != nil {
		return nil, fmt.Errorf("attachTodoTags0: %w", err)
	}

	return todoTags1, nil
}

func (todo0 *Todo) InsertTags(ctx context.Context, exec bob.Executor, related ...*TagSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	inserted, err := Tags.Insert(bob.ToMods(related...)).All(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}
	tags2 := TagSlice(inserted)

	_, err = attachTodoTags0(ctx, exec, len(related), todo0, tags2)
	if err != nil {
		return err
	}

	todo0.R.Tags = append(todo0.R.Tags, tags2...)

	for _, rel := range tags2 {
		rel.R.Todos = append(rel.R.Todos, todo0)
	}
	return nil
}

func (todo0 *Todo) AttachTags(ctx context.Context, exec bob.Executor, related ...*Tag) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	tags2 := TagSlice(related)

	_, err = attachTodoTags0(ctx, exec, len(related), todo0, tags2)
	if err != nil {
		return err
	}

	todo0.R.Tags = append(todo0.R.Tags, tags2...)

	for _, rel := range related {
		rel.R.Todos = append(rel.R.Todos, todo0)
	}

	return nil
}

func attachTodoUser0(ctx context.Context, exec bob.Executor, count int, todo0 *Todo, user1 *User) (*Todo, error) {
	setter := &TodoSetter{
		UserID: omit.From(user1.ID),
	}

	err := todo0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTodoUser0: %w", err)
	}

	return todo0, nil
}

func (todo0 *Todo) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTodoUser0(ctx, exec, 1, todo0, user1)
	if err != nil {
		return err
	}

	todo0.R.User = user1

	user1.R.Todos = append(user1.R.Todos, todo0)

	return nil
}

func (todo0 *Todo) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachTodoUser0(ctx, exec, 1, todo0, user1)
	if err != nil {
		return err
	}

	todo0.R.User = user1

	user1.R.Todos = append(user1.R.Todos, todo0)

	return nil
}

type todoWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, uuid.UUID]
	UserID      psql.WhereMod[Q, uuid.UUID]
	Title       psql.WhereMod[Q, string]
	Description psql.WhereNullMod[Q, string]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
	Status      psql.WhereMod[Q, string]
	DueDate     psql.WhereNullMod[Q, time.Time]
	SortOrder   psql.WhereMod[Q, float64]
}

func (todoWhere[Q]) AliasedAs(alias string) todoWhere[Q] {
	return buildTodoWhere[Q](buildTodoColumns(alias))
}

func buildTodoWhere[Q psql.Filterable](cols todoColumns) todoWhere[Q] {
	return todoWhere[Q]{
		ID:          psql.Where[Q, uuid.UUID](cols.ID),
		UserID:      psql.Where[Q, uuid.UUID](cols.UserID),
		Title:       psql.Where[Q, string](cols.Title),
		Description: psql.WhereNull[Q, string](cols.Description),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt),
		Status:      psql.Where[Q, string](cols.Status),
		DueDate:     psql.WhereNull[Q, time.Time](cols.DueDate),
		SortOrder:   psql.Where[Q, float64](cols.SortOrder),
	}
}

func (o *Todo) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Tags":
		rels, ok := retrieved.(TagSlice)
		if !ok {
			return fmt.Errorf("todo cannot load %T as %q", retrieved, name)
		}

		o.R.Tags = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Todos = TodoSlice{o}
			}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("todo cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Todos = TodoSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("todo has no relationship %q", name)
	}
}

type todoPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildTodoPreloader() todoPreloader {
	return todoPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        Todos,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type todoThenLoader[Q orm.Loadable] struct {
	Tags func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTodoThenLoader[Q orm.Loadable]() todoThenLoader[Q] {
	type TagsLoadInterface interface {
		LoadTags(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return todoThenLoader[Q]{
		Tags: thenLoadBuilder[Q](
			"Tags",
			func(ctx context.Context, exec bob.Executor, retrieved TagsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTags(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadTags loads the todo's Tags into the .R struct
func (o *Todo) LoadTags(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Tags = nil

	related, err := o.Tags(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Todos = TodoSlice{o}
	}

	o.R.Tags = related
	return nil
}

// LoadTags loads the todo's Tags into the .R struct
func (os TodoSlice) LoadTags(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// since we are changing the columns, we need to check if the original columns were set or add the defaults
	sq := dialect.SelectQuery{}
	for _, mod := range mods {
		mod.Apply(&sq)
	}

	if len(sq.SelectList.Columns) == 0 {
		mods = append(mods, sm.Columns(Tags.Columns))
	}

	q := os.Tags(append(
		mods,
		sm.Columns(TodoTags.Columns.TodoID.As("related_todos.ID")),
	)...)

	IDSlice := []uuid.UUID{}

	mapper := scan.Mod(scan.StructMapper[*Tag](), func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any, any) error) {
		return func(row *scan.Row) (any, error) {
				IDSlice = append(IDSlice, *new(uuid.UUID))
				row.ScheduleScanByName("related_todos.ID", &IDSlice[len(IDSlice)-1])

				return nil, nil
			},
			func(any, any) error {
				return nil
			}
	})

	tags, err := bob.Allx[bob.SliceTransformer[*Tag, TagSlice]](ctx, exec, q, mapper)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Tags = nil
	}

	for _, o := range os {
		for i, rel := range tags {
			if !(o.ID == IDSlice[i]) {
				continue
			}

			rel.R.Todos = append(rel.R.Todos, o)

			o.R.Tags = append(o.R.Tags, rel)
		}
	}

	return nil
}

// LoadUser loads the todo's User into the .R struct
func (o *Todo) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Todos = TodoSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the todo's User into the .R struct
func (os TodoSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			rel.R.Todos = append(rel.R.Todos, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type todoJoins[Q dialect.Joinable] struct {
	typ  string
	Tags modAs[Q, tagColumns]
	User modAs[Q, userColumns]
}

func (j todoJoins[Q]) aliasedAs(alias string) todoJoins[Q] {
	return buildTodoJoins[Q](buildTodoColumns(alias), j.typ)
}

func buildTodoJoins[Q dialect.Joinable](cols todoColumns, typ string) todoJoins[Q] {
	return todoJoins[Q]{
		typ: typ,
		Tags: modAs[Q, tagColumns]{
			c: Tags.Columns,
			f: func(to tagColumns) bob.Mod[Q] {
				random := strconv.FormatInt(randInt(), 10)
				mods := make(mods.QueryMods[Q], 0, 2)

				{
					to := TodoTags.Columns.AliasedAs(TodoTags.Columns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, TodoTags.Name().As(to.Alias())).On(
						to.TodoID.EQ(cols.ID),
					))
				}
				{
					cols := TodoTags.Columns.AliasedAs(TodoTags.Columns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, Tags.Name().As(to.Alias())).On(
						to.ID.EQ(cols.TagID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
