// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// TodoTag is an object representing the database table.
type TodoTag struct {
	TodoID uuid.UUID `db:"todo_id,pk" `
	TagID  uuid.UUID `db:"tag_id,pk" `

	R todoTagR `db:"-" `
}

// TodoTagSlice is an alias for a slice of pointers to TodoTag.
// This should almost always be used instead of []*TodoTag.
type TodoTagSlice []*TodoTag

// TodoTags contains methods to work with the todo_tags table
var TodoTags = psql.NewTablex[*TodoTag, TodoTagSlice, *TodoTagSetter]("", "todo_tags", buildTodoTagColumns("todo_tags"))

// TodoTagsQuery is a query on the todo_tags table
type TodoTagsQuery = *psql.ViewQuery[*TodoTag, TodoTagSlice]

// todoTagR is where relationships are stored.
type todoTagR struct {
	Tag  *Tag  // todo_tags.fk_todo_tags_tag_id
	Todo *Todo // todo_tags.fk_todo_tags_todo_id
}

func buildTodoTagColumns(alias string) todoTagColumns {
	return todoTagColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"todo_id", "tag_id",
		).WithParent("todo_tags"),
		tableAlias: alias,
		TodoID:     psql.Quote(alias, "todo_id"),
		TagID:      psql.Quote(alias, "tag_id"),
	}
}

type todoTagColumns struct {
	expr.ColumnsExpr
	tableAlias string
	TodoID     psql.Expression
	TagID      psql.Expression
}

func (c todoTagColumns) Alias() string {
	return c.tableAlias
}

func (todoTagColumns) AliasedAs(alias string) todoTagColumns {
	return buildTodoTagColumns(alias)
}

// TodoTagSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TodoTagSetter struct {
	TodoID omit.Val[uuid.UUID] `db:"todo_id,pk" `
	TagID  omit.Val[uuid.UUID] `db:"tag_id,pk" `
}

func (s TodoTagSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if s.TodoID.IsValue() {
		vals = append(vals, "todo_id")
	}
	if s.TagID.IsValue() {
		vals = append(vals, "tag_id")
	}
	return vals
}

func (s TodoTagSetter) Overwrite(t *TodoTag) {
	if s.TodoID.IsValue() {
		t.TodoID = s.TodoID.MustGet()
	}
	if s.TagID.IsValue() {
		t.TagID = s.TagID.MustGet()
	}
}

func (s *TodoTagSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return TodoTags.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 2)
		if s.TodoID.IsValue() {
			vals[0] = psql.Arg(s.TodoID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.TagID.IsValue() {
			vals[1] = psql.Arg(s.TagID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s TodoTagSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TodoTagSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if s.TodoID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "todo_id")...),
			psql.Arg(s.TodoID),
		}})
	}

	if s.TagID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "tag_id")...),
			psql.Arg(s.TagID),
		}})
	}

	return exprs
}

// FindTodoTag retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTodoTag(ctx context.Context, exec bob.Executor, TodoIDPK uuid.UUID, TagIDPK uuid.UUID, cols ...string) (*TodoTag, error) {
	if len(cols) == 0 {
		return TodoTags.Query(
			sm.Where(TodoTags.Columns.TodoID.EQ(psql.Arg(TodoIDPK))),
			sm.Where(TodoTags.Columns.TagID.EQ(psql.Arg(TagIDPK))),
		).One(ctx, exec)
	}

	return TodoTags.Query(
		sm.Where(TodoTags.Columns.TodoID.EQ(psql.Arg(TodoIDPK))),
		sm.Where(TodoTags.Columns.TagID.EQ(psql.Arg(TagIDPK))),
		sm.Columns(TodoTags.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TodoTagExists checks the presence of a single record by primary key
func TodoTagExists(ctx context.Context, exec bob.Executor, TodoIDPK uuid.UUID, TagIDPK uuid.UUID) (bool, error) {
	return TodoTags.Query(
		sm.Where(TodoTags.Columns.TodoID.EQ(psql.Arg(TodoIDPK))),
		sm.Where(TodoTags.Columns.TagID.EQ(psql.Arg(TagIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after TodoTag is retrieved from the database
func (o *TodoTag) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = TodoTags.AfterSelectHooks.RunHooks(ctx, exec, TodoTagSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = TodoTags.AfterInsertHooks.RunHooks(ctx, exec, TodoTagSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = TodoTags.AfterUpdateHooks.RunHooks(ctx, exec, TodoTagSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = TodoTags.AfterDeleteHooks.RunHooks(ctx, exec, TodoTagSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the TodoTag
func (o *TodoTag) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.TodoID,
		o.TagID,
	)
}

func (o *TodoTag) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("todo_tags", "todo_id"), psql.Quote("todo_tags", "tag_id")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the TodoTag
func (o *TodoTag) Update(ctx context.Context, exec bob.Executor, s *TodoTagSetter) error {
	v, err := TodoTags.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single TodoTag record with an executor
func (o *TodoTag) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := TodoTags.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the TodoTag using the executor
func (o *TodoTag) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := TodoTags.Query(
		sm.Where(TodoTags.Columns.TodoID.EQ(psql.Arg(o.TodoID))),
		sm.Where(TodoTags.Columns.TagID.EQ(psql.Arg(o.TagID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TodoTagSlice is retrieved from the database
func (o TodoTagSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = TodoTags.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = TodoTags.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = TodoTags.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = TodoTags.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TodoTagSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("todo_tags", "todo_id"), psql.Quote("todo_tags", "tag_id")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TodoTagSlice) copyMatchingRows(from ...*TodoTag) {
	for i, old := range o {
		for _, new := range from {
			if new.TodoID != old.TodoID {
				continue
			}
			if new.TagID != old.TagID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TodoTagSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return TodoTags.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *TodoTag:
				o.copyMatchingRows(retrieved)
			case []*TodoTag:
				o.copyMatchingRows(retrieved...)
			case TodoTagSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a TodoTag or a slice of TodoTag
				// then run the AfterUpdateHooks on the slice
				_, err = TodoTags.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TodoTagSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return TodoTags.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *TodoTag:
				o.copyMatchingRows(retrieved)
			case []*TodoTag:
				o.copyMatchingRows(retrieved...)
			case TodoTagSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a TodoTag or a slice of TodoTag
				// then run the AfterDeleteHooks on the slice
				_, err = TodoTags.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TodoTagSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TodoTagSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := TodoTags.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TodoTagSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := TodoTags.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TodoTagSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := TodoTags.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Tag starts a query for related objects on tags
func (o *TodoTag) Tag(mods ...bob.Mod[*dialect.SelectQuery]) TagsQuery {
	return Tags.Query(append(mods,
		sm.Where(Tags.Columns.ID.EQ(psql.Arg(o.TagID))),
	)...)
}

func (os TodoTagSlice) Tag(mods ...bob.Mod[*dialect.SelectQuery]) TagsQuery {
	pkTagID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkTagID = append(pkTagID, o.TagID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkTagID), "uuid[]")),
	))

	return Tags.Query(append(mods,
		sm.Where(psql.Group(Tags.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Todo starts a query for related objects on todos
func (o *TodoTag) Todo(mods ...bob.Mod[*dialect.SelectQuery]) TodosQuery {
	return Todos.Query(append(mods,
		sm.Where(Todos.Columns.ID.EQ(psql.Arg(o.TodoID))),
	)...)
}

func (os TodoTagSlice) Todo(mods ...bob.Mod[*dialect.SelectQuery]) TodosQuery {
	pkTodoID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkTodoID = append(pkTodoID, o.TodoID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkTodoID), "uuid[]")),
	))

	return Todos.Query(append(mods,
		sm.Where(psql.Group(Todos.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachTodoTagTag0(ctx context.Context, exec bob.Executor, count int, todoTag0 *TodoTag, tag1 *Tag) (*TodoTag, error) {
	setter := &TodoTagSetter{
		TagID: omit.From(tag1.ID),
	}

	err := todoTag0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTodoTagTag0: %w", err)
	}

	return todoTag0, nil
}

func (todoTag0 *TodoTag) InsertTag(ctx context.Context, exec bob.Executor, related *TagSetter) error {
	var err error

	tag1, err := Tags.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTodoTagTag0(ctx, exec, 1, todoTag0, tag1)
	if err != nil {
		return err
	}

	todoTag0.R.Tag = tag1

	return nil
}

func (todoTag0 *TodoTag) AttachTag(ctx context.Context, exec bob.Executor, tag1 *Tag) error {
	var err error

	_, err = attachTodoTagTag0(ctx, exec, 1, todoTag0, tag1)
	if err != nil {
		return err
	}

	todoTag0.R.Tag = tag1

	return nil
}

func attachTodoTagTodo0(ctx context.Context, exec bob.Executor, count int, todoTag0 *TodoTag, todo1 *Todo) (*TodoTag, error) {
	setter := &TodoTagSetter{
		TodoID: omit.From(todo1.ID),
	}

	err := todoTag0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTodoTagTodo0: %w", err)
	}

	return todoTag0, nil
}

func (todoTag0 *TodoTag) InsertTodo(ctx context.Context, exec bob.Executor, related *TodoSetter) error {
	var err error

	todo1, err := Todos.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTodoTagTodo0(ctx, exec, 1, todoTag0, todo1)
	if err != nil {
		return err
	}

	todoTag0.R.Todo = todo1

	return nil
}

func (todoTag0 *TodoTag) AttachTodo(ctx context.Context, exec bob.Executor, todo1 *Todo) error {
	var err error

	_, err = attachTodoTagTodo0(ctx, exec, 1, todoTag0, todo1)
	if err != nil {
		return err
	}

	todoTag0.R.Todo = todo1

	return nil
}

type todoTagWhere[Q psql.Filterable] struct {
	TodoID psql.WhereMod[Q, uuid.UUID]
	TagID  psql.WhereMod[Q, uuid.UUID]
}

func (todoTagWhere[Q]) AliasedAs(alias string) todoTagWhere[Q] {
	return buildTodoTagWhere[Q](buildTodoTagColumns(alias))
}

func buildTodoTagWhere[Q psql.Filterable](cols todoTagColumns) todoTagWhere[Q] {
	return todoTagWhere[Q]{
		TodoID: psql.Where[Q, uuid.UUID](cols.TodoID),
		TagID:  psql.Where[Q, uuid.UUID](cols.TagID),
	}
}

func (o *TodoTag) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Tag":
		rel, ok := retrieved.(*Tag)
		if !ok {
			return fmt.Errorf("todoTag cannot load %T as %q", retrieved, name)
		}

		o.R.Tag = rel

		return nil
	case "Todo":
		rel, ok := retrieved.(*Todo)
		if !ok {
			return fmt.Errorf("todoTag cannot load %T as %q", retrieved, name)
		}

		o.R.Todo = rel

		return nil
	default:
		return fmt.Errorf("todoTag has no relationship %q", name)
	}
}

type todoTagPreloader struct {
	Tag  func(...psql.PreloadOption) psql.Preloader
	Todo func(...psql.PreloadOption) psql.Preloader
}

func buildTodoTagPreloader() todoTagPreloader {
	return todoTagPreloader{
		Tag: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Tag, TagSlice](psql.PreloadRel{
				Name: "Tag",
				Sides: []psql.PreloadSide{
					{
						From:        TodoTags,
						To:          Tags,
						FromColumns: []string{"tag_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Tags.Columns.Names(), opts...)
		},
		Todo: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Todo, TodoSlice](psql.PreloadRel{
				Name: "Todo",
				Sides: []psql.PreloadSide{
					{
						From:        TodoTags,
						To:          Todos,
						FromColumns: []string{"todo_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Todos.Columns.Names(), opts...)
		},
	}
}

type todoTagThenLoader[Q orm.Loadable] struct {
	Tag  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Todo func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTodoTagThenLoader[Q orm.Loadable]() todoTagThenLoader[Q] {
	type TagLoadInterface interface {
		LoadTag(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TodoLoadInterface interface {
		LoadTodo(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return todoTagThenLoader[Q]{
		Tag: thenLoadBuilder[Q](
			"Tag",
			func(ctx context.Context, exec bob.Executor, retrieved TagLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTag(ctx, exec, mods...)
			},
		),
		Todo: thenLoadBuilder[Q](
			"Todo",
			func(ctx context.Context, exec bob.Executor, retrieved TodoLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTodo(ctx, exec, mods...)
			},
		),
	}
}

// LoadTag loads the todoTag's Tag into the .R struct
func (o *TodoTag) LoadTag(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Tag = nil

	related, err := o.Tag(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.Tag = related
	return nil
}

// LoadTag loads the todoTag's Tag into the .R struct
func (os TodoTagSlice) LoadTag(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	tags, err := os.Tag(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range tags {

			if !(o.TagID == rel.ID) {
				continue
			}

			o.R.Tag = rel
			break
		}
	}

	return nil
}

// LoadTodo loads the todoTag's Todo into the .R struct
func (o *TodoTag) LoadTodo(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Todo = nil

	related, err := o.Todo(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.Todo = related
	return nil
}

// LoadTodo loads the todoTag's Todo into the .R struct
func (os TodoTagSlice) LoadTodo(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	todos, err := os.Todo(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range todos {

			if !(o.TodoID == rel.ID) {
				continue
			}

			o.R.Todo = rel
			break
		}
	}

	return nil
}

type todoTagJoins[Q dialect.Joinable] struct {
	typ  string
	Tag  modAs[Q, tagColumns]
	Todo modAs[Q, todoColumns]
}

func (j todoTagJoins[Q]) aliasedAs(alias string) todoTagJoins[Q] {
	return buildTodoTagJoins[Q](buildTodoTagColumns(alias), j.typ)
}

func buildTodoTagJoins[Q dialect.Joinable](cols todoTagColumns, typ string) todoTagJoins[Q] {
	return todoTagJoins[Q]{
		typ: typ,
		Tag: modAs[Q, tagColumns]{
			c: Tags.Columns,
			f: func(to tagColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Tags.Name().As(to.Alias())).On(
						to.ID.EQ(cols.TagID),
					))
				}

				return mods
			},
		},
		Todo: modAs[Q, todoColumns]{
			c: Todos.Columns,
			f: func(to todoColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Todos.Name().As(to.Alias())).On(
						to.ID.EQ(cols.TodoID),
					))
				}

				return mods
			},
		},
	}
}
