// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// User is an object representing the database table.
type User struct {
	ID          uuid.UUID        `db:"id,pk" `
	Name        string           `db:"name" `
	Email       string           `db:"email" `
	CreatedAt   time.Time        `db:"created_at" `
	UpdatedAt   time.Time        `db:"updated_at" `
	FirebaseUID null.Val[string] `db:"firebase_uid" `

	R userR `db:"-" `
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = psql.NewTablex[*User, UserSlice, *UserSetter]("", "users", buildUserColumns("users"))

// UsersQuery is a query on the users table
type UsersQuery = *psql.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	APIKeys APIKeySlice // api_keys.fk_api_keys_user_id
	Tags    TagSlice    // tags.fk_tags_user_id
	Todos   TodoSlice   // todos.fk_todos_user_id
}

func buildUserColumns(alias string) userColumns {
	return userColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "email", "created_at", "updated_at", "firebase_uid",
		).WithParent("users"),
		tableAlias:  alias,
		ID:          psql.Quote(alias, "id"),
		Name:        psql.Quote(alias, "name"),
		Email:       psql.Quote(alias, "email"),
		CreatedAt:   psql.Quote(alias, "created_at"),
		UpdatedAt:   psql.Quote(alias, "updated_at"),
		FirebaseUID: psql.Quote(alias, "firebase_uid"),
	}
}

type userColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          psql.Expression
	Name        psql.Expression
	Email       psql.Expression
	CreatedAt   psql.Expression
	UpdatedAt   psql.Expression
	FirebaseUID psql.Expression
}

func (c userColumns) Alias() string {
	return c.tableAlias
}

func (userColumns) AliasedAs(alias string) userColumns {
	return buildUserColumns(alias)
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID          omit.Val[uuid.UUID]  `db:"id,pk" `
	Name        omit.Val[string]     `db:"name" `
	Email       omit.Val[string]     `db:"email" `
	CreatedAt   omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt   omit.Val[time.Time]  `db:"updated_at" `
	FirebaseUID omitnull.Val[string] `db:"firebase_uid" `
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Email.IsValue() {
		vals = append(vals, "email")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if !s.FirebaseUID.IsUnset() {
		vals = append(vals, "firebase_uid")
	}
	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Email.IsValue() {
		t.Email = s.Email.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if !s.FirebaseUID.IsUnset() {
		t.FirebaseUID = s.FirebaseUID.MustGetNull()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Email.IsValue() {
			vals[2] = psql.Arg(s.Email.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[3] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[4] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.FirebaseUID.IsUnset() {
			vals[5] = psql.Arg(s.FirebaseUID.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Email.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if !s.FirebaseUID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "firebase_uid")...),
			psql.Arg(s.FirebaseUID),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Users.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the User
func (o *User) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return psql.Quote("users", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	v, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("users", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// APIKeys starts a query for related objects on api_keys
func (o *User) APIKeys(mods ...bob.Mod[*dialect.SelectQuery]) APIKeysQuery {
	return APIKeys.Query(append(mods,
		sm.Where(APIKeys.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) APIKeys(mods ...bob.Mod[*dialect.SelectQuery]) APIKeysQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return APIKeys.Query(append(mods,
		sm.Where(psql.Group(APIKeys.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// Tags starts a query for related objects on tags
func (o *User) Tags(mods ...bob.Mod[*dialect.SelectQuery]) TagsQuery {
	return Tags.Query(append(mods,
		sm.Where(Tags.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) Tags(mods ...bob.Mod[*dialect.SelectQuery]) TagsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Tags.Query(append(mods,
		sm.Where(psql.Group(Tags.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// Todos starts a query for related objects on todos
func (o *User) Todos(mods ...bob.Mod[*dialect.SelectQuery]) TodosQuery {
	return Todos.Query(append(mods,
		sm.Where(Todos.Columns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) Todos(mods ...bob.Mod[*dialect.SelectQuery]) TodosQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Todos.Query(append(mods,
		sm.Where(psql.Group(Todos.Columns.UserID).OP("IN", PKArgExpr)),
	)...)
}

func insertUserAPIKeys0(ctx context.Context, exec bob.Executor, apiKeys1 []*APIKeySetter, user0 *User) (APIKeySlice, error) {
	for i := range apiKeys1 {
		apiKeys1[i].UserID = omit.From(user0.ID)
	}

	ret, err := APIKeys.Insert(bob.ToMods(apiKeys1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserAPIKeys0: %w", err)
	}

	return ret, nil
}

func attachUserAPIKeys0(ctx context.Context, exec bob.Executor, count int, apiKeys1 APIKeySlice, user0 *User) (APIKeySlice, error) {
	setter := &APIKeySetter{
		UserID: omit.From(user0.ID),
	}

	err := apiKeys1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserAPIKeys0: %w", err)
	}

	return apiKeys1, nil
}

func (user0 *User) InsertAPIKeys(ctx context.Context, exec bob.Executor, related ...*APIKeySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	apiKeys1, err := insertUserAPIKeys0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.APIKeys = append(user0.R.APIKeys, apiKeys1...)

	for _, rel := range apiKeys1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachAPIKeys(ctx context.Context, exec bob.Executor, related ...*APIKey) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	apiKeys1 := APIKeySlice(related)

	_, err = attachUserAPIKeys0(ctx, exec, len(related), apiKeys1, user0)
	if err != nil {
		return err
	}

	user0.R.APIKeys = append(user0.R.APIKeys, apiKeys1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserTags0(ctx context.Context, exec bob.Executor, tags1 []*TagSetter, user0 *User) (TagSlice, error) {
	for i := range tags1 {
		tags1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Tags.Insert(bob.ToMods(tags1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserTags0: %w", err)
	}

	return ret, nil
}

func attachUserTags0(ctx context.Context, exec bob.Executor, count int, tags1 TagSlice, user0 *User) (TagSlice, error) {
	setter := &TagSetter{
		UserID: omit.From(user0.ID),
	}

	err := tags1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserTags0: %w", err)
	}

	return tags1, nil
}

func (user0 *User) InsertTags(ctx context.Context, exec bob.Executor, related ...*TagSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	tags1, err := insertUserTags0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Tags = append(user0.R.Tags, tags1...)

	for _, rel := range tags1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachTags(ctx context.Context, exec bob.Executor, related ...*Tag) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	tags1 := TagSlice(related)

	_, err = attachUserTags0(ctx, exec, len(related), tags1, user0)
	if err != nil {
		return err
	}

	user0.R.Tags = append(user0.R.Tags, tags1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserTodos0(ctx context.Context, exec bob.Executor, todos1 []*TodoSetter, user0 *User) (TodoSlice, error) {
	for i := range todos1 {
		todos1[i].UserID = omit.From(user0.ID)
	}

	ret, err := Todos.Insert(bob.ToMods(todos1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserTodos0: %w", err)
	}

	return ret, nil
}

func attachUserTodos0(ctx context.Context, exec bob.Executor, count int, todos1 TodoSlice, user0 *User) (TodoSlice, error) {
	setter := &TodoSetter{
		UserID: omit.From(user0.ID),
	}

	err := todos1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserTodos0: %w", err)
	}

	return todos1, nil
}

func (user0 *User) InsertTodos(ctx context.Context, exec bob.Executor, related ...*TodoSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	todos1, err := insertUserTodos0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Todos = append(user0.R.Todos, todos1...)

	for _, rel := range todos1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachTodos(ctx context.Context, exec bob.Executor, related ...*Todo) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	todos1 := TodoSlice(related)

	_, err = attachUserTodos0(ctx, exec, len(related), todos1, user0)
	if err != nil {
		return err
	}

	user0.R.Todos = append(user0.R.Todos, todos1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

type userWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, uuid.UUID]
	Name        psql.WhereMod[Q, string]
	Email       psql.WhereMod[Q, string]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
	FirebaseUID psql.WhereNullMod[Q, string]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q psql.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		ID:          psql.Where[Q, uuid.UUID](cols.ID),
		Name:        psql.Where[Q, string](cols.Name),
		Email:       psql.Where[Q, string](cols.Email),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt),
		FirebaseUID: psql.WhereNull[Q, string](cols.FirebaseUID),
	}
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "APIKeys":
		rels, ok := retrieved.(APIKeySlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.APIKeys = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "Tags":
		rels, ok := retrieved.(TagSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Tags = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "Todos":
		rels, ok := retrieved.(TodoSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Todos = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

type userPreloader struct{}

func buildUserPreloader() userPreloader {
	return userPreloader{}
}

type userThenLoader[Q orm.Loadable] struct {
	APIKeys func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Tags    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Todos   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserThenLoader[Q orm.Loadable]() userThenLoader[Q] {
	type APIKeysLoadInterface interface {
		LoadAPIKeys(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TagsLoadInterface interface {
		LoadTags(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TodosLoadInterface interface {
		LoadTodos(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userThenLoader[Q]{
		APIKeys: thenLoadBuilder[Q](
			"APIKeys",
			func(ctx context.Context, exec bob.Executor, retrieved APIKeysLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAPIKeys(ctx, exec, mods...)
			},
		),
		Tags: thenLoadBuilder[Q](
			"Tags",
			func(ctx context.Context, exec bob.Executor, retrieved TagsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTags(ctx, exec, mods...)
			},
		),
		Todos: thenLoadBuilder[Q](
			"Todos",
			func(ctx context.Context, exec bob.Executor, retrieved TodosLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTodos(ctx, exec, mods...)
			},
		),
	}
}

// LoadAPIKeys loads the user's APIKeys into the .R struct
func (o *User) LoadAPIKeys(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.APIKeys = nil

	related, err := o.APIKeys(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.APIKeys = related
	return nil
}

// LoadAPIKeys loads the user's APIKeys into the .R struct
func (os UserSlice) LoadAPIKeys(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	apiKeys, err := os.APIKeys(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.APIKeys = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range apiKeys {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.APIKeys = append(o.R.APIKeys, rel)
		}
	}

	return nil
}

// LoadTags loads the user's Tags into the .R struct
func (o *User) LoadTags(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Tags = nil

	related, err := o.Tags(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Tags = related
	return nil
}

// LoadTags loads the user's Tags into the .R struct
func (os UserSlice) LoadTags(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	tags, err := os.Tags(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Tags = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range tags {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Tags = append(o.R.Tags, rel)
		}
	}

	return nil
}

// LoadTodos loads the user's Todos into the .R struct
func (o *User) LoadTodos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Todos = nil

	related, err := o.Todos(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Todos = related
	return nil
}

// LoadTodos loads the user's Todos into the .R struct
func (os UserSlice) LoadTodos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	todos, err := os.Todos(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Todos = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range todos {

			if !(o.ID == rel.UserID) {
				continue
			}

			rel.R.User = o

			o.R.Todos = append(o.R.Todos, rel)
		}
	}

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ     string
	APIKeys modAs[Q, apiKeyColumns]
	Tags    modAs[Q, tagColumns]
	Todos   modAs[Q, todoColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ: typ,
		APIKeys: modAs[Q, apiKeyColumns]{
			c: APIKeys.Columns,
			f: func(to apiKeyColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, APIKeys.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Tags: modAs[Q, tagColumns]{
			c: Tags.Columns,
			f: func(to tagColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Tags.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Todos: modAs[Q, todoColumns]{
			c: Todos.Columns,
			f: func(to todoColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Todos.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
