// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var APIKeys = Table[
	apiKeyColumns,
	apiKeyIndexes,
	apiKeyForeignKeys,
	apiKeyUniques,
	apiKeyChecks,
]{
	Schema: "",
	Name:   "api_keys",
	Columns: apiKeyColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "gen_random_uuid()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		KeyHash: column{
			Name:      "key_hash",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: apiKeyIndexes{
		APIKeysPkey: index{
			Type: "btree",
			Name: "api_keys_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		APIKeysKeyHashKey: index{
			Type: "btree",
			Name: "api_keys_key_hash_key",
			Columns: []indexColumn{
				{
					Name:         "key_hash",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxAPIKeysKeyHash: index{
			Type: "btree",
			Name: "idx_api_keys_key_hash",
			Columns: []indexColumn{
				{
					Name:         "key_hash",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "api_keys_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: apiKeyForeignKeys{
		APIKeysFKAPIKeysUserID: foreignKey{
			constraint: constraint{
				Name:    "api_keys.fk_api_keys_user_id",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: apiKeyUniques{
		APIKeysKeyHashKey: constraint{
			Name:    "api_keys_key_hash_key",
			Columns: []string{"key_hash"},
			Comment: "",
		},
	},

	Comment: "APIキー",
}

type apiKeyColumns struct {
	ID        column
	UserID    column
	Name      column
	CreatedAt column
	KeyHash   column
}

func (c apiKeyColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Name, c.CreatedAt, c.KeyHash,
	}
}

type apiKeyIndexes struct {
	APIKeysPkey       index
	APIKeysKeyHashKey index
	IdxAPIKeysKeyHash index
}

func (i apiKeyIndexes) AsSlice() []index {
	return []index{
		i.APIKeysPkey, i.APIKeysKeyHashKey, i.IdxAPIKeysKeyHash,
	}
}

type apiKeyForeignKeys struct {
	APIKeysFKAPIKeysUserID foreignKey
}

func (f apiKeyForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.APIKeysFKAPIKeysUserID,
	}
}

type apiKeyUniques struct {
	APIKeysKeyHashKey constraint
}

func (u apiKeyUniques) AsSlice() []constraint {
	return []constraint{
		u.APIKeysKeyHashKey,
	}
}

type apiKeyChecks struct{}

func (c apiKeyChecks) AsSlice() []check {
	return []check{}
}
