// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Tags = Table[
	tagColumns,
	tagIndexes,
	tagForeignKeys,
	tagUniques,
	tagChecks,
]{
	Schema: "",
	Name:   "tags",
	Columns: tagColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "gen_random_uuid()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: tagIndexes{
		TagsPkey: index{
			Type: "btree",
			Name: "tags_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "tags_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: tagForeignKeys{
		TagsTagsUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "tags.tags_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type tagColumns struct {
	ID        column
	UserID    column
	Name      column
	CreatedAt column
	UpdatedAt column
}

func (c tagColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Name, c.CreatedAt, c.UpdatedAt,
	}
}

type tagIndexes struct {
	TagsPkey index
}

func (i tagIndexes) AsSlice() []index {
	return []index{
		i.TagsPkey,
	}
}

type tagForeignKeys struct {
	TagsTagsUserIDFkey foreignKey
}

func (f tagForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.TagsTagsUserIDFkey,
	}
}

type tagUniques struct{}

func (u tagUniques) AsSlice() []constraint {
	return []constraint{}
}

type tagChecks struct{}

func (c tagChecks) AsSlice() []check {
	return []check{}
}
