// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var TodoTags = Table[
	todoTagColumns,
	todoTagIndexes,
	todoTagForeignKeys,
	todoTagUniques,
	todoTagChecks,
]{
	Schema: "",
	Name:   "todo_tags",
	Columns: todoTagColumns{
		TodoID: column{
			Name:      "todo_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TagID: column{
			Name:      "tag_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: todoTagIndexes{
		TodoTagsPkey: index{
			Type: "btree",
			Name: "todo_tags_pkey",
			Columns: []indexColumn{
				{
					Name:         "todo_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "tag_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "todo_tags_pkey",
		Columns: []string{"todo_id", "tag_id"},
		Comment: "",
	},
	ForeignKeys: todoTagForeignKeys{
		TodoTagsFKTodoTagsTagID: foreignKey{
			constraint: constraint{
				Name:    "todo_tags.fk_todo_tags_tag_id",
				Columns: []string{"tag_id"},
				Comment: "",
			},
			ForeignTable:   "tags",
			ForeignColumns: []string{"id"},
		},
		TodoTagsFKTodoTagsTodoID: foreignKey{
			constraint: constraint{
				Name:    "todo_tags.fk_todo_tags_todo_id",
				Columns: []string{"todo_id"},
				Comment: "",
			},
			ForeignTable:   "todos",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "ToDoとタグの中間テーブル",
}

type todoTagColumns struct {
	TodoID column
	TagID  column
}

func (c todoTagColumns) AsSlice() []column {
	return []column{
		c.TodoID, c.TagID,
	}
}

type todoTagIndexes struct {
	TodoTagsPkey index
}

func (i todoTagIndexes) AsSlice() []index {
	return []index{
		i.TodoTagsPkey,
	}
}

type todoTagForeignKeys struct {
	TodoTagsFKTodoTagsTagID  foreignKey
	TodoTagsFKTodoTagsTodoID foreignKey
}

func (f todoTagForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.TodoTagsFKTodoTagsTagID, f.TodoTagsFKTodoTagsTodoID,
	}
}

type todoTagUniques struct{}

func (u todoTagUniques) AsSlice() []constraint {
	return []constraint{}
}

type todoTagChecks struct{}

func (c todoTagChecks) AsSlice() []check {
	return []check{}
}
