// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Todos = Table[
	todoColumns,
	todoIndexes,
	todoForeignKeys,
	todoUniques,
	todoChecks,
]{
	Schema: "",
	Name:   "todos",
	Columns: todoColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "gen_random_uuid()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Title: column{
			Name:      "title",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Done: column{
			Name:      "done",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: todoIndexes{
		TodosPkey: index{
			Type: "btree",
			Name: "todos_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "todos_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: todoForeignKeys{
		TodosTodosUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "todos.todos_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type todoColumns struct {
	ID          column
	UserID      column
	Title       column
	Description column
	Done        column
	CreatedAt   column
	UpdatedAt   column
}

func (c todoColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.Title, c.Description, c.Done, c.CreatedAt, c.UpdatedAt,
	}
}

type todoIndexes struct {
	TodosPkey index
}

func (i todoIndexes) AsSlice() []index {
	return []index{
		i.TodosPkey,
	}
}

type todoForeignKeys struct {
	TodosTodosUserIDFkey foreignKey
}

func (f todoForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.TodosTodosUserIDFkey,
	}
}

type todoUniques struct{}

func (u todoUniques) AsSlice() []constraint {
	return []constraint{}
}

type todoChecks struct{}

func (c todoChecks) AsSlice() []check {
	return []check{}
}
