// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Users = Table[
	userColumns,
	userIndexes,
	userForeignKeys,
	userUniques,
	userChecks,
]{
	Schema: "",
	Name:   "users",
	Columns: userColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "gen_random_uuid()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Email: column{
			Name:      "email",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		FirebaseUID: column{
			Name:      "firebase_uid",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userIndexes{
		UsersPkey: index{
			Type: "btree",
			Name: "users_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersEmailKey: index{
			Type: "btree",
			Name: "users_email_key",
			Columns: []indexColumn{
				{
					Name:         "email",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UsersFirebaseUIDKey: index{
			Type: "btree",
			Name: "users_firebase_uid_key",
			Columns: []indexColumn{
				{
					Name:         "firebase_uid",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "users_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: userUniques{
		UsersEmailKey: constraint{
			Name:    "users_email_key",
			Columns: []string{"email"},
			Comment: "",
		},
		UsersFirebaseUIDKey: constraint{
			Name:    "users_firebase_uid_key",
			Columns: []string{"firebase_uid"},
			Comment: "",
		},
	},

	Comment: "ユーザー情報",
}

type userColumns struct {
	ID          column
	Name        column
	Email       column
	CreatedAt   column
	UpdatedAt   column
	FirebaseUID column
}

func (c userColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Email, c.CreatedAt, c.UpdatedAt, c.FirebaseUID,
	}
}

type userIndexes struct {
	UsersPkey           index
	UsersEmailKey       index
	UsersFirebaseUIDKey index
}

func (i userIndexes) AsSlice() []index {
	return []index{
		i.UsersPkey, i.UsersEmailKey, i.UsersFirebaseUIDKey,
	}
}

type userForeignKeys struct{}

func (f userForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type userUniques struct {
	UsersEmailKey       constraint
	UsersFirebaseUIDKey constraint
}

func (u userUniques) AsSlice() []constraint {
	return []constraint{
		u.UsersEmailKey, u.UsersFirebaseUIDKey,
	}
}

type userChecks struct{}

func (c userChecks) AsSlice() []check {
	return []check{}
}
