// Code generated by kessoku. DO NOT EDIT.

package di

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/jimi024rion/todo-go/backend/internal/domain/todo/repository"
	"github.com/jimi024rion/todo-go/backend/internal/domain/tx"
	"github.com/jimi024rion/todo-go/backend/internal/infrastructure/rdb"
	todo0 "github.com/jimi024rion/todo-go/backend/internal/infrastructure/rdb/repository/todo"
	"github.com/jimi024rion/todo-go/backend/internal/presentation/handler"
	"github.com/jimi024rion/todo-go/backend/internal/presentation/http"
	"github.com/jimi024rion/todo-go/backend/internal/presentation/http/health"
	todo1 "github.com/jimi024rion/todo-go/backend/internal/presentation/http/todo"
	"github.com/jimi024rion/todo-go/backend/internal/presentation/http/user"
	todo2 "github.com/jimi024rion/todo-go/backend/internal/usecase/todo"
	user0 "github.com/jimi024rion/todo-go/backend/internal/usecase/user"
	"github.com/mazrean/kessoku"
	"github.com/stephenafamo/bob"
	"golang.org/x/sync/errgroup"
)

func InitializeServer(ctx context.Context, db bob.DB) *gin.Engine {
	var (
		healthCheckHandler *health.HealthCheckHandler
		createUserUsecase  *user0.CreateUserUsecase
		handler0           *health.Handler
		createUserHandler  *user.CreateUserHandler
		repository         *todo0.Repository
		repositoryCh       = make(chan struct{})
		txManager          tx.TxManager
		handler1           *user.Handler
		listUseCase        *todo2.ListUseCase
		getUseCase         *todo2.GetUseCase
		updateUseCase      *todo2.UpdateUseCase
		deleteUseCase      *todo2.DeleteUseCase
		createUseCase      *todo2.CreateUseCase
		listHandler        *todo1.ListHandler
		getHandler         *todo1.GetHandler
		updateHandler      *todo1.UpdateHandler
		deleteHandler      *todo1.DeleteHandler
		createHandler      *todo1.CreateHandler
		createHandlerCh    = make(chan struct{})
		handler2           *todo1.Handler
		handler3           *handler.Handler
		engine             *gin.Engine
	)
	eg, ctx := errgroup.WithContext(ctx)
	eg.Go(func() error {
		txManager = kessoku.Async(kessoku.Async(kessoku.Provide(rdb.NewTxManager))).Fn()(db)
		select {
		case <-repositoryCh:
		case <-ctx.Done():
			return ctx.Err()
		}
		createUseCase = kessoku.Provide(todo2.NewCreateUseCase).Fn()(repository, txManager)
		createHandler = kessoku.Provide(todo1.NewCreateHandler).Fn()(createUseCase)
		close(createHandlerCh)
		return nil
	})
	healthCheckHandler = kessoku.Provide(health.NewHealthCheckHandler).Fn()()
	createUserUsecase = kessoku.Provide(user0.NewCreateUserUsecase).Fn()()
	handler0 = kessoku.Provide(health.NewHandler).Fn()(healthCheckHandler)
	createUserHandler = kessoku.Provide(user.NewCreateUserHandler).Fn()(createUserUsecase)
	repository = kessoku.Bind[todo.TodoRepository](kessoku.Async(kessoku.Provide(todo0.NewRepository))).Fn()(db)
	close(repositoryCh)
	handler1 = kessoku.Provide(user.NewHandler).Fn()(createUserHandler)
	listUseCase = kessoku.Provide(todo2.NewListUseCase).Fn()(repository)
	getUseCase = kessoku.Provide(todo2.NewGetUseCase).Fn()(repository)
	updateUseCase = kessoku.Provide(todo2.NewUpdateUseCase).Fn()(repository)
	deleteUseCase = kessoku.Provide(todo2.NewDeleteUseCase).Fn()(repository)
	listHandler = kessoku.Provide(todo1.NewListHandler).Fn()(listUseCase)
	getHandler = kessoku.Provide(todo1.NewGetHandler).Fn()(getUseCase)
	updateHandler = kessoku.Provide(todo1.NewUpdateHandler).Fn()(updateUseCase)
	deleteHandler = kessoku.Provide(todo1.NewDeleteHandler).Fn()(deleteUseCase)
	<-createHandlerCh
	handler2 = kessoku.Provide(todo1.NewHandler).Fn()(listHandler, createHandler, getHandler, updateHandler, deleteHandler)
	handler3 = kessoku.Provide(handler.NewHandler).Fn()(handler0, handler1, handler2)
	engine = kessoku.Provide(http.NewRouter).Fn()(handler3)
	_ = eg.Wait()
	return engine
}
